<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Zend\\Diactoros\\' => array($vendorDir . '/zendframework/zend-diactoros/src'),
    'SparkPost\\Test\\TestUtils\\' => array($vendorDir . '/sparkpost/php-sparkpost/test/unit/TestUtils'),
    'SparkPost\\SendGridCompatibility\\' => array($vendorDir . '/sparkpost/php-sparkpost/lib/SendGridCompatibility'),
    'SparkPost\\' => array($vendorDir . '/sparkpost/php-sparkpost/lib/SparkPost'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Ivory\\HttpAdapter\\' => array($vendorDir . '/egeloen/http-adapter/src'),
);
